# Generated by Django 4.2 on 2023-04-26 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='categotyThrough',
            new_name='categoryThrough',
        ),
    ]
